{% set version = "2025.6.15" %}

package:
  name: ca-certificates
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/certifi/certifi-{{ version }}.tar.gz
  sha256: d747aa5a8b9bbbb1bb8c22bb13e22bd1f18e9796defa16bab421f7f7a317323b

build:
  number: 0
  noarch: generic

requirements:
  run:
    - __unix   # [unix]
    - __win    # [win]

test:
  requires:
    - curl

  commands:
    # Verify the certificates are there.
    - test -f "${PREFIX}/ssl/cacert.pem"                                      # [unix]
    - test -f "${PREFIX}/ssl/cert.pem"                                        # [unix]
    - if not exist %LIBRARY_PREFIX%\\ssl\\cacert.pem exit 1                   # [win]
    - if not exist %LIBRARY_PREFIX%\\ssl\\cert.pem exit 1                     # [win]

    # Use the certificates to download something.
    - curl --cacert "${PREFIX}/ssl/cacert.pem" https://www.google.com         # [unix]
    - curl --cacert %LIBRARY_PREFIX%\\ssl\\cacert.pem https://www.google.com  # [win]

about:
  home: https://github.com/conda-forge/ca-certificates-feedstock
  license: ISC
  license_file: LICENSE
  summary: Certificates for use with other packages.

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - mwcraig
    - ocefpaf
    - patricksnape
    - pelson
    - scopatz
